//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TopFootballersDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopFootballersTable
    {
        public int ID { get; set; }
        public string Player_Name { get; set; }
        public string Age { get; set; }
        public string Place_of_Birth { get; set; }
        public string Height { get; set; }
        public string Playing_Position { get; set; }
        public string Current_Team { get; set; }
        public string National_Team { get; set; }
        public string Description { get; set; }
        public string Picture { get; set; }
    }
}
