//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public string Name { get; set; }
        public string Address { get; set; }
        public string Town { get; set; }
        public string Postcode { get; set; }
        public string Phone { get; set; }
    }
}
