<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="WebForm2.aspx.cs" Inherits="WebApplication5.WebForm2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <asp:Panel ID="Panel1" runat="server">
            <asp:Repeater ID="rptOrders" runat="server">
    <HeaderTemplate>
        <table cellspacing="0" rules="all" border="1">
            <tr>
                <th scope="col" style="width: 80px">
                    Item
                </th>
                <th scope="col" style="width: 120px">
                    Quantity
                </th>
                <th scope="col" style="width: 100px">
                    Shipping
                </th>
            </tr>
    </HeaderTemplate>
    <ItemTemplate>
        <tr>
            <td>
                <asp:Label ID="lblItem" runat="server" Text='<%# Eval("Item") %>' />
            </td>
            <td>
                <asp:Label ID="lblQuantity" runat="server" Text='<%# Eval("Quantity") %>' />
            </td>
            <td>
                <asp:Label ID="lblShipping" runat="server" Text='<%# Eval("Shipping") %>' />
            </td>
        </tr>
    </ItemTemplate>
    <FooterTemplate>
        </table>
    </FooterTemplate>
</asp:Repeater>
            <asp:Button ID="Button1" runat="server" OnClick="AddOrder" Text="Add Order" />
            <br />
        </asp:Panel>
        <asp:Panel ID="Panel2" runat="server">
        <asp:Repeater ID="rptDetails" runat="server">
    <HeaderTemplate>
        <table cellspacing="0" rules="all" border="1">
            <tr>
                <th scope="col" style="width: 80px">
                    Name
                </th>
                <th scope="col" style="width: 120px">
                    Address
                </th>
                <th scope="col" style="width: 100px">
                    Town
                </th>
                <th scope="col" style="width: 100px">
                    Postcode
                </th>
                <th scope="col" style="width: 100px">
                    Phone
                </th>
            </tr>
    </HeaderTemplate>
    <ItemTemplate>
        <tr>
            <td>
                <asp:Label ID="lblName" runat="server" Text='<%# Eval("Name") %>' />
            </td>
            <td>
                <asp:Label ID="lblAddress" runat="server" Text='<%# Eval("Address") %>' />
            </td>
            <td>
                <asp:Label ID="lblTown" runat="server" Text='<%# Eval("Town") %>' />
            </td>
            <td>
                <asp:Label ID="lblPostcode" runat="server" Text='<%# Eval("Postcode") %>' />
            </td>
            <td>
                <asp:Label ID="lblPhone" runat="server" Text='<%# Eval("Phone") %>' />
            </td>
        </tr>
    </ItemTemplate>
    <FooterTemplate>
        </table>
    </FooterTemplate>
    </asp:Repeater>
    </asp:Panel>
        <asp:GridView ID="GridView1" runat="server" DataSourceID="SqlDataSource1" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" CellPadding="4" ForeColor="#333333" GridLines="None">
            <AlternatingRowStyle BackColor="White"></AlternatingRowStyle>
            <Columns>
                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name"></asp:BoundField>
                <asp:BoundField DataField="Address" HeaderText="Address" SortExpression="Address"></asp:BoundField>
                <asp:BoundField DataField="Town" HeaderText="Town" SortExpression="Town"></asp:BoundField>
                <asp:BoundField DataField="Postcode" HeaderText="Postcode" SortExpression="Postcode"></asp:BoundField>
                <asp:BoundField DataField="Phone" HeaderText="Phone" SortExpression="Phone"></asp:BoundField>
            </Columns>
            <EditRowStyle BackColor="#2461BF"></EditRowStyle>

            <FooterStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White"></FooterStyle>

            <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White"></HeaderStyle>

            <PagerStyle HorizontalAlign="Center" BackColor="#2461BF" ForeColor="White"></PagerStyle>

            <RowStyle BackColor="#EFF3FB"></RowStyle>

            <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333"></SelectedRowStyle>

            <SortedAscendingCellStyle BackColor="#F5F7FB"></SortedAscendingCellStyle>

            <SortedAscendingHeaderStyle BackColor="#6D95E1"></SortedAscendingHeaderStyle>

            <SortedDescendingCellStyle BackColor="#E9EBEF"></SortedDescendingCellStyle>

            <SortedDescendingHeaderStyle BackColor="#4870BE"></SortedDescendingHeaderStyle>
        </asp:GridView>
        <asp:SqlDataSource runat="server" ID="SqlDataSource1" ConnectionString='<%$ ConnectionStrings:ConnectionString %>' SelectCommand="SELECT * FROM [customer] WHERE ([Name] = @Name)">
            <SelectParameters>
                <asp:QueryStringParameter QueryStringField="Name" DefaultValue="" Name="Name" Type="String"></asp:QueryStringParameter>
            </SelectParameters>
        </asp:SqlDataSource>
    </div>
    </form>
</body>
</html>